### ISSUE TITLE
沿革パターンのアイテムの増やし方を複製固定にしたほうが良いか（検討）

### ISSUE THREAD

**Issue by kutsu123** [m-g-n/ruijinen-plugin_block-patterns--r001-corp#79]
沿革パターンで新しい年を増やそうとすると、年まではかんたんに増やせるが、月の表記部分はすでにあるのからコピペしてもってくるしかない。
LPパターン集の「お客様の声」パターンのように、追加ボタンの非表示・複製でしか追加できませんメッセージ にしたほうがやさしいかもしれない

## 現状

https://user-images.githubusercontent.com/15826102/173549405-79117681-45df-4b0f-b29b-1dfffeffec60.mov

## 参考 - LPパターンのお客様の声の場合
![スクリーンショット 2022-06-14 18 53 39](https://user-images.githubusercontent.com/15826102/173549699-ee9c4bf0-be9c-40d2-b16a-67dbbdb77015.png)

**Comment by xiuca** [comment]
@kutsu123 さん
確かにそうだと思います！年・月まとめて複製スタイルが一番手間が少ない気がしています。
（特に段落を追加してコピペ、みたいなところが…）
